### ISSUE TITLE
Latex in dot points?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/sphinxcontrib-jupyter#103]
I'm having an issue with rendering of some text in `optgrowth.rst`

It looks like this for some reason:

<img width="771" alt="screen shot 2018-09-17 at 12 40 37 pm" src="https://user-images.githubusercontent.com/21038129/45636901-0f938200-ba77-11e8-8137-d24deed4e5a0.png">

**Comment by mmcky** [comment]
@natashawatkins that is due to an error in the source ``rst`` file. This extension is a bit more picky than the ``html`` renderer. That line in the source is indented by 4 spaces which means it get's interpreted as a block quote. 

Are you using the latest version of ``jupinx``? as the inline math issue within blockquotes should be fixed.
![image](https://user-images.githubusercontent.com/8263752/45656355-4675a080-bb28-11e8-942a-c3dfd3880e4c.png)
It is changing daily at the moment.

**Comment by mmcky** [comment]
I am not sure why ``greedy`` is on the right of `v*` though.

**Comment by natashawatkins** [comment]
That's how it's meant to look, it was changing it for some reason in my example

**Comment by mmcky** [comment]
@natashawatkins it used to be broken in ``japing`` but made it a bit more robust to spacing issues so got fixed a few days ago.

**Comment by natashawatkins** [comment]
@mmcky does that mean that this issue will also be fixed, from the arellano lecture...

<img width="778" alt="screen shot 2018-09-24 at 3 33 29 pm" src="https://user-images.githubusercontent.com/21038129/45974712-27877a80-c010-11e8-8ce3-25d661942157.png">

**Comment by natashawatkins** [comment]
Another example from `perm_income`

<img width="741" alt="screen shot 2018-09-24 at 5 48 52 pm" src="https://user-images.githubusercontent.com/21038129/45981206-30814780-c022-11e8-9ab1-16568d3d09b1.png">
